#############################################
# Output
#############################################

output_dir: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/results_AML_new"

#############################################
# Required inputs
#############################################

RNA_TPM_file: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/AML_TPM.tsv"
breakpoints: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/breakpoints.tsv"
CNAs: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/CNAs.tsv"

gtf: /omics/groups/OE0219/internal/Etienne/data/reference/Homo_sapiens.GRCh37.87.gtf.gz
chr_arms: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/data/chr_arms_hg19.txt"


#############################################
# Optional but strongly recommended inputs
#############################################

# Directory containing the output of gatk ASEReadcounter (one tsv file per sample)
ase_dir: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/ASEreadcounter"
# ase_dna_dir will only be used for plotting the DNA VAF compared to the RNA VAF.
#ase_dna_dir: ""

# Allele-specific expression will be ignored for imprinted genes, if they are provided.
imprinted_genes_file: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/data/imprinted_genes.txt"

# pyjacker looks for SVs in the same TAD as a gene (+ a margin). 
# If not TADs are provided, it will look for SVs which are up to max_dist_bp2tss from the TSS.
TADs_file: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/data/HSPC_TADs.bed"
#max_dist_bp2tss: 1500000 


##############################################
# Additional parameters
#############################################

weight_expnormal: 0
weight_amplification: 0
#weight_deletion: 0
n_iterations_FDR: 30

# Provide fusion transcripts (used for annotating the results)
fusions: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/fusions_merged.tsv"

# Provide enhancers (used for annotating the results)
enhancers: "/omics/groups/OE0219/internal/Etienne/tools/pyjacker/AML_data/enhancers.tsv"


#RNA_TPM_other_samples: /omics/groups/OE0219/internal/Etienne/tools/pyjacker/data/TCGA_Beat_cellLines_TPM.tsv
RNA_TPM_normal_samples: /omics/groups/OE0219/internal/Etienne/tools/pyjacker/data/ImmuneCells_TPM.tsv





